Feature get top users
usfcs-perf-eng-s20/heroku-project-favs pull request #8
Opened 2020-03-19 03:21 UTC by jwahjudi

2020-03-19 04:12 UTC, mosopeogundipe commented on src/cs/usfca/edu/histfavcheckout/controller/HistFavCheckoutHandler.java
> +		System.out.println("hello " + users);
Remove print statement used for debugging

2020-03-19 04:17 UTC, mosopeogundipe requested changes

2020-03-19 04:17 UTC, mosopeogundipe commented on src/cs/usfca/edu/histfavcheckout/controller/HistFavCheckoutHandler.java
> +		if(page*nums-1<=result.size()) {
This wouldn't work if page = 0. 
In that case, the result populated [here ](https://github.com/usfcs-perf-eng-s20/heroku-project-favs/pull/8/files#diff-0fae860ae0c1e35be827d26bc884c318R156) will most likely be an empty list

Whereas Page =0 is a valid value. Maybe have a special logic that handles page=0

2020-03-19 04:17 UTC, mosopeogundipe commented on src/cs/usfca/edu/histfavcheckout/controller/HistFavCheckoutHandler.java
> +		System.out.println("hello " + users);
Remove print statement used for debugging

2020-03-19 04:47 UTC, kedarkhetia commented
Can we also squash all the commits to 1?

Something like this. 
https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

I see a lot of dead code in lot of these commits. You might want to squash them all and then make a pull request with relevant commit message.

2020-03-19 06:51 UTC, mosopeogundipe approved these changes

2020-03-19 06:57 UTC, kedarkhetia requested changes
Can we also squash all the commits to 1?

Something like this.
https://github.com/todotxt/todo.txt-android/wiki/Squash-All-Commits-Related-to-a-Single-Issue-into-a-Single-Commit

I see a lot of dead code in lot of these commits. You might want to squash them all and then make a pull request with relevant commit message.

Also remove .DS_Store files (you can do that by adding them into .gitignore). Also, remove the target class file. It seems that your base branch is behind master because of which you are facing these conflicts with master.

2020-03-21 03:44 UTC, kedarkhetia requested changes
I see a lot of changes that are already present in the master (from other authors). We should avoid adding duplicate code as much as possible. Especially since these changes are part of your CR, for the features you were never assigned, I would not be comfortable approving it. 

My suggestion would be to just deprecate this branch. Create a new branch from the current master branch as base and redo your portion of the changes in it. After you verify create a new pull request and we can take a look.

2020-03-21 04:03 UTC, mosopeogundipe commented
> 
> 
> I see a lot of changes that are already present in the master (from other authors). We should avoid adding duplicate code as much as possible. Especially since these changes are part of your CR, for the features you were never assigned, I would not be comfortable approving it.
> 
> My suggestion would be to just deprecate this branch. Create a new branch from the current master branch as base and redo your portion of the changes in it. After you verify create a new pull request and we can take a look.

Yes, I agree with this. @jwahjudi let's try to:
1) Create a new branch based on master 
2) Copy/paste your changes into the new branch
3) Make a pull request based for the changes you added in (2) above

That will both solve ensure you can merge seamlessly and also wouldn't ascribe code changes done by others to you.

2020-03-22 04:54 UTC, jwahjudi commented
I squash the debugging codes, but for some reason

2020-03-22 04:54 UTC, closed without merging